[General]
ReportStats=true

[UartEndpoint px4]
Device=/dev/ttyACM0
Baud=115200

[UdpEndpoint in]
Mode=Server
Address=127.0.0.1
Port=14540

[UdpEndpoint monitor]
Mode=Normal
Address=127.0.0.1
Port=14542

[UdpEndpoint missionplanner]
Mode=Normal
Address=10.140.27.96
Port=14550
